### ISSUE TITLE
AUR package tint3-cpp-git failing to build on 32-bit system

### ISSUE THREAD

**Issue by mcfadzgit** [jmc-88/tint3#10]
When trying to makepkg latest commit b00a82b with AUR tint3-cpp-git PKGBUILD I get the following failure (though it builds fine on a 64-bit system):
http://pastebin.com/3qST1Tsy

**Comment by jmc-88** [comment]
Not having a 32 bit machine around I didn't catch this early. However, it was easy to fix. Thanks for reporting the issue!

**Comment by mcfadzgit** [comment]
Many thanks for fixing this problem so quickly. I still have a handful of 32-bit systems to support, and I always update them _after_ the 64-bit systems - that's why I had not noticed the problem before!
