### ISSUE TITLE
Deadlock in signal handler

### ISSUE THREAD

**Issue by o9000** [jmc-88/tint3#12]
The startup notification code is calling the functions sn_launcher_context_complete() and sn_launcher_context_unref() (also util::log::Error() but not sure about that one) from a signal handler. These functions call in turn other functions from Xlib, which may block.

Calling any potentially blocking function from a signal handler is forbidden, as it may cause a deadlock.  Even if a deadlock does not happen, there might be races.

The solution is to only communicate the event from signal handler to the event loop, and run the handling code there. The event loop might be blocking in select() so it needs to be woken up.

This can be achieved by using a non-blocking pipe: the signal handler writes a byte into the pipe, while the event loop selects on both the X11 socket and the pipe.

Reference: http://cr.yp.to/docs/selfpipe.html

Here is a fix: https://gitlab.com/o9000/tint3/commit/d3205e7ab534752ae4a87d2ad9a675ac016f301b

The only thing I'm not sure of is in which file to define SigchldHandler(). src/util/x11.cc might not be the best place.

**Comment by jmc-88** [comment]
Well, your tint3 clone seems gone (my bad for letting this sit for so long, I guess).

I've recreated the fix as best as I can. Still seems to work, so I'm going to push it.

**Comment by o9000** [comment]
I'm sorry, I forgot to make the repo public. It should work now. From a quick look over your commit, there are no reads from the pipe. You need that, otherwise the buffer will get full once enough signals have been received.

**Comment by jmc-88** [comment]
Ah, fail. Never code while sleepy.
