### ISSUE TITLE
Authors missing

### ISSUE THREAD

**Issue by o9000** [jmc-88/tint3#14]
I'm not sure if this is right or not, but I don't think it's nice to remove the names of previous authors and contributors from the AUTHORS file, as some of the old code is still in use. Maybe re-add them and list them as previous authors or something?

The commit was cc633d8

**Comment by o9000** [comment]
Related: you changed the license to GPLv3, but tint2 was GPLv2 only. If you look at the header of tint.cc, it says "you can redistribute it and/or modify it under the terms of the GNU General Public License version 2" it does not say "version 2 _or later_". Thus it is not possible to upgrade the license to a newer version without the consent of all previous authors and contributors. It's the same problem the Linux kernel had.

Not trying to nitpick here, but this is the way it is...

**Comment by jmc-88** [comment]
I got lost in the amount of authors and previous authors and previous authors (as this is a fork of a fork) and at some point cleaned it up. That was also the point where I thought I would've been the one and only user of this thing; my bad, that was not the right thing to do and I apologize, I'll change the AUTHORS file.

As for the license, you're correct. I didn't carefully check the headers at the time (I did now) and I was under the impression it had the "or later" statement. I'll change the license file back to GPLv2.

**Comment by o9000** [comment]
No apologies needed :) It's just that if tint3 is going to be picked up by distros, the license needs to be in order. Some, such as Debian, are quite pedantic about this stuff.

**Comment by o9000** [comment]
Looking at the first post in this bug report, I sounded a bit cold, that was not my intention; it was just brevity.

Also not sure that I said this: thank you for all your efforts to clean up the code, this was a much needed task. Although as you say you are doing it as a hobby and did not expect anyone else to use it, the fact that you made your changes public is much appreciated.

**Comment by jmc-88** [comment]
No worries, I didn't take the comment as cold, but you were right on both points. :)
