### ISSUE TITLE
Low battery command doesn't seem to be executed

### ISSUE THREAD

**Issue by mcfadzgit** [jmc-88/tint3#15]
Am running tint3 from commit dfb6242 on Asus netbook laptop running Arch Linux 64-bit.
With the following section in tint3rc the battery_low_cmd does not seem to be activated when battery charge falls below 20% (or other setting):

```
# Battery
battery = 1
battery_low_status = 20
battery_low_cmd = notify-send -u critical "Danger: battery low"
battery_hide = 0
bat1_font = Liberation Sans Bold 9
bat2_font = Liberation Sans 9
battery_font_color = #FFFFFF 100
battery_padding = 1 1
battery_background_id = 1
```

This definitely worked with tint2-git Arch package a while ago.
Apart from this problem, the battery feature seems to work fine in tint3.

**Comment by jmc-88** [comment]
My bad, I tried to change the way programs are executed by spawning the executables directly, but then we'd need to also parse the entire command line to split the arguments to pass to execlp(), etc... Best to change it back to how it was and have it launch the specified commands through /bin/sh.

**Comment by mcfadzgit** [comment]
Many thanks for fixing this promptly.
