### ISSUE TITLE
Autohide doesn't work

### ISSUE THREAD

**Issue by loserMcloser** [jmc-88/tint3#17]
Setting autohide = 1 results in the following output (each repeated several times):

 -> Xlib error (3): BadWindow (invalid Window parameter)
Programming error: timeout already deleted

**Comment by jmc-88** [comment]
I'll mark this fixed as the new code seems to work fine for what I could test locally (both on a modified config of mine, and on the one you attached in #18 ). Please reopen if the problem still persists.
