### ISSUE TITLE
floating point exception

### ISSUE THREAD

**Issue by loserMcloser** [jmc-88/tint3#18]
The following config results in a core dump with a "floating point exception" error. Commenting out one of the "panel_background_id" and "launcher_item_app" lines makes it work.

[tint3-error.txt](https://github.com/jmc-88/tint3/files/348464/tint3-error.txt)

**Comment by jmc-88** [comment]
I haven't managed to trigger a core dump on this config (other than the segfault from #19, but no FPE yet). How to reproduce?

**Comment by loserMcloser** [comment]
Just running tint3 -c that-attached-config-file causes it to abort on my system.

I rebuilt with debug symbols and ran it with gdb, here is the output. (Built using git commit 89bfde65e81d5a82a471194afad06aad71836fd2. FYI, yes #19 is fixed on my system with this build.)

[tint3-SIGFPE-gdb.txt](https://github.com/jmc-88/tint3/files/351023/tint3-SIGFPE-gdb.txt)

**Comment by jmc-88** [comment]
Alright, I missed the actual .desktop file that was referenced in your config, I'm now able to reproduce.
