### ISSUE TITLE
Seg fault on interrupt

### ISSUE THREAD

**Issue by loserMcloser** [jmc-88/tint3#19]
Hitting <ctrl>-c on a running tint3 process causes a seg fault.

**Comment by jmc-88** [comment]
I only get an Xlib error, but no segfault.
Maybe related to some particular config file? Is it reproducible with the config file posted for https://github.com/jmc-88/tint3/issues/18?

**Comment by jmc-88** [comment]
Confirmed, I can reproduce with that config.

**Comment by jmc-88** [comment]
Thanks for reporting the issue. Should be fixed now, please try to recompile the binary from the latest Git head.
