### ISSUE TITLE
Ignore disabled video outputs

### ISSUE THREAD

**Issue by o9000** [jmc-88/tint3#20]
Hi there,

I found a bug in tint2 that might affect tint3 too: it does not ignore disabled video outputs, which are returned by XRRGetCrtcInfo with width and height set to zero according to the randr documentation: https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt#n1010

A change should be made around this line https://github.com/jmc-88/tint3/blob/master/src/server.cc#L222 to ignore such outputs. Otherwise we'll try to create a panel with size zero for a monitor that doesn't exist, that eventually leads to some strange problems.

Reference: https://gitlab.com/o9000/tint2/issues/618

**Comment by jmc-88** [comment]
Thanks, I'll fix that asap.
