### ISSUE TITLE
Bug in GetIcon

### ISSUE THREAD

**Issue by o9000** [jmc-88/tint3#21]
When _NET_WM_ICON is set but empty, data is not NULL, but the length is zero. However the code only checks for NULL; GetIconCount() returns correctly zero; but GetBestIcon assumes non-zero length and then performs some small out of bounds accesses. This may set both w and h to negative numbers, in which case this is followed by a large oob read to fill in icon_data.

This can be tested with the program `fldigi`, but a script to set an empty _NET_WM_ICON to any window could probably trigger it too.

A quick fix is to add the correct checks. But the problem is that GetIcon/GetIconCount/GetBestIcon contain some really crappy code...

A different issue, a few lines after, is that imlib_create_image_using_copied_data is necessary in i386 too. Since we're about to XFree the buffer afterwards.

**Comment by jmc-88** [comment]
Really, the problem is that imlib2 sucks (though it's ubiquitous...). Thanks for the report, I'll see if I can fix this properly.

**Comment by o9000** [comment]
This is what I did: https://gitlab.com/o9000/tint2/blob/master/src/taskbar/task.c#L280

**Comment by jmc-88** [comment]
Unrelated, but: what does the "[if (0 && img)](https://gitlab.com/o9000/tint2/blame/master/src/taskbar/task.c#L290)" accomplish?

**Comment by o9000** [comment]
Eh. It's some old debug code I've used a couple of times. There should have been a variable like debug_wm_icons instead of the zero. But I've been too lazy to do it properly. I don't #ifdef it out since I want to keep it compiling; the optimizer should eliminate the dead code.
