### ISSUE TITLE
Feature suggestion - Mouse Over Effect

### ISSUE THREAD

**Issue by ghost** [jmc-88/tint3#3]
Something like this:
https://code.google.com/p/tint2/issues/detail?id=44

**Comment by jmc-88** [comment]
As answered on the other issue, I'd like to have a stable binary before looking into the cosmetics. Other than that, it might be doable I suppose.

**Comment by jmc-88** [comment]
https://github.com/jmc-88/tint3/commit/0c711f437f2e3589290ce35180ac6bbed88f9ff4 is also related. I forgot to tag this issue in the commit description.

**Comment by jmc-88** [comment]
And I forgot again: https://github.com/jmc-88/tint3/commit/a717866121d0ae6498cf6e634fe8d09b0a6b0a18

**Comment by jmc-88** [comment]
I believe this is complete now.
