### ISSUE TITLE
Panel does not show up if margins are set to zero or width is %

### ISSUE THREAD

**Issue by jggouvea** [jmc-88/tint3#39]
I am using tint3 in my ArchLinux box, running under Pekwm 0.17 (from standard repos now). The package I use is tint3-cpp-git from AUR. The first time I compiled tint3-cpp-git I was using Pekwm-git from AUR too, but I have recompiled tint3 after I downgraded to packaged Pekwm (the current pekwm-git on AUR is buggy).

Now tint3 is complaining that "true" is not valid for items that are set to be "boolean" (but "0" and "1" both work as expected).

And, what is more important, the panel doesn't appear if margins are set to "0 0" or width is a percentage. If width is specified as an integer (whatever) it shows, but occupying 100% of screen width. If margins are set greater than 0 for both, the panel appears, but, as expected, windows appear above it.

Here I include my tint3rc

```
# Default tint3 configuration file.
#
# For information on manually configuring tint3 see:
#   https://github.com/jmc-88/tint3

# {{{ backgrounds
# ID 1
rounded = 2
border_width = 0
background_color = #dddddd 80
border_color = #dddddd 0

# ID 2
rounded = 1
border_width = 0
background_color = #efefef 0
background_color_hover = #7f7f7f 40
background_color_pressed = #7f7f7f 70
border_color = #000000 0

# ID 3
rounded = 0
border_width = 0
background_color = #ffcc00 80
border_color = #000000 0

# ID 4
rounded = 0
border_width = 0
background_color = #3f3f3f 90
border_color = #000000 0
# }}} backgrounds

# {{{ panel
panel_monitor = all
panel_position =  top left horizontal
panel_size = 26 26
panel_margin =  1 1
panel_padding = 0 0 0
panel_dock = 0
wm_menu = 1
panel_layer = top
panel_background_id = 1
panel_items = LTSC
# }}} panel

# {{{ taskbar
taskbar_mode = multi_desktop
taskbar_padding = 0 0 0
taskbar_background_id = 1
taskbar_active_background_id = 0
# }}} taskbar

# {{{ tasks
urgent_nb_of_blink = 20
task_icon = 1
task_text = 1 
task_centered = 0
task_maximum_size = 440 16
task_padding = 0 2 6 
task_background_id = 1
task_tooltip = 1
task_active_background_id = 3
task_urgent_background_id = 2
task_active_font_color = #616161
task_font_color = #000000
task_font = tooltip_font = Iosevka Type Slab 9
task_iconified_background_id = 2
# }}} tasks

# {{{ task icons
task_icon_asb = 100 0 0
task_active_icon_asb = 100 0 0
task_urgent_icon_asb = 100 0 0
task_iconified_icon_asb = 100 0 0
# }}} task icons

# {{{ system tray
#systray = 1
systray_padding = 0 2 6
systray_sort = right2left
systray_background_id = 2
systray_icon_size = 16
systray_icon_asb = 100 0 0
# }}} system tray

# {{{ battery
battery = 0
# }}} battery

# {{{ clock
#clock = 1
time1_format = %H:%M
time1_font = Sans 10
clock_font_color = #0f0000
#clock_background = 3
clock_padding = 10
clock_lclick_command = qarma --calendar
# }}} clock

# {{{ tooltips
tooltip = 1
tooltip_padding = 2 2
tooltip_show_timeout = 0.0
tooltip_hide_timeout = 0.0
tooltip_background_id = 2
tooltip_font = Iosevka Type Slab 9
tooltip_font_color = #616161 100
# }}} tooltips

# {{{ mouse
mouse_middle = none
mouse_right = close
mouse_scroll_up = toggle
mouse_scroll_down = iconify
mouse_effects = 1
mouse_hover_icon_asb = 100 0 25
mouse_pressed_icon_asb = 100 0 -25
# }}} mouse

# {{{ launchers
launcher_icon_size = 24
launcher_icon_theme = Delft
launcher_tooltip = 1
launcher_item_app = $HOME/.local/share/applications/menu.desktop
# }}} launchers
#
font_shadow = 1
strut_policy = follow_size
```

I hope this report is constructive to debugging and improving tint3.

Anyway, thank you for writing this software!

**Comment by jmc-88** [comment]
Hi, thanks for taking the time to compile this bug report!

> Now tint3 is complaining that "true" is not valid for items that are set to be "boolean" (but "0" and "1" both work as expected).

That's weird, the configuration parser is supposed to allow these (I've also added a [test case](https://github.com/jmc-88/tint3/blob/master/src/config_test.cc#L303) for it), can you remember which configuration key was rejecting `true` as a value?

> And, what is more important, the panel doesn't appear if margins are set to "0 0" or width is a percentage. If width is specified as an integer (whatever) it shows, but occupying 100% of screen width. If margins are set greater than 0 for both, the panel appears, but, as expected, windows appear above it.

Hmm, I'll have to test this out. You say:

> If width is specified as an integer (whatever) it shows, but occupying 100% of screen width

which somehow still sounds like configuration parsing issues, but I'd have to see it in action. The configuration you posted here is the working one? What were the values of `panel_size` and 
`panel_margin` in the broken case?

(Note: I'm travelling so I might be slow to respond to future updates to this issue.)

**Comment by jggouvea** [comment]
This is the working configuration. 

The clock , clock_background and systray keys need to be commented. If I uncomment them, tint3 does not show up.

Panel margin does not work if you set to '0 0'

Panel size doesn't work if you set to '100% 24' (whatever the second number). 

It works (occupying 100% of width) if you set any integer width ('240 24', for example).

In any case, tint3 does not crash, it starts, but remains unseen (perhaps out of the screen real estate).

**Comment by jmc-88** [comment]
So far I managed to reproduce only the issues regarding `panel_size`, which should be fixed in c893a29b5fdb9a35c59f5451156ac1e77b139084.

Boolean values I've tested seem to work with a literal `true` or `false` just fine. The panel seems to show fine for me on my box, regardless of the values of `clock`, `clock_background` or `systray`.
Can you maybe try rerunning a version of tint3 that includes the above commit and see if it's still an issue? Thanks.

**Comment by jggouvea** [comment]
Right. I will recompile the package and test it.

**Comment by jmc-88** [comment]
Hi José, any luck on this?

**Comment by jmc-88** [comment]
Having heard no updates, I'm going to assume this is fixed. Please reopen if the issue still occurs!
