### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by Vakhrushev** [jmc-88/tint3#4]
Tool tip is shown at the bottom but the panel is at the top

<pre>
# Tint2 config file
# Generated by tintwizard (http://code.google.com/p/tintwizard/)
# For information on manually configuring tint2 see http://code.google.com/p/tint2/wiki/Configure

# To use this as default tint2 config: save as $HOME/.config/tint2/tint2rc

# Background definitions
# ID 1
rounded = 0
border_width = 0
background_color = #151515 30
border_color = #4E4242 100

# ID 2
rounded = 0
border_width = 0
background_color = #000000 100
border_color = #FFFFFF 100

# ID 3
rounded = 0
border_width = 2
background_color = #000000 70
border_color = #4173DE 61

# Panel
panel_monitor = all
panel_position = bottom left horizontal
panel_size = 100% 20
panel_margin = 0 0
panel_padding = 4 0 0
panel_dock = 1
wm_menu = 1
panel_layer = top
panel_background_id = 1

# Panel Autohide
autohide = 0
autohide_show_timeout = 0.0
autohide_hide_timeout = 0.0
autohide_height = 0
strut_policy = none

# Taskbar
taskbar_mode = single_desktop
taskbar_padding = 0 0 0
taskbar_background_id = 2
taskbar_active_background_id = 0

# Tasks
urgent_nb_of_blink = 7
task_icon = 1
task_text = 0
task_centered = 0
task_maximum_size = 25 16
task_padding = 1 1
task_background_id = 0
task_active_background_id = 0
task_urgent_background_id = 0
task_iconified_background_id = 0

# Task Icons
task_icon_asb = 70 -20 0
task_active_icon_asb = 100 0 50
task_urgent_icon_asb = 100 0 0
task_iconified_icon_asb = 40 0 -10

# Fonts
task_font = Consolas 11
task_font_color = #888888 100
task_active_font_color = #FFFFFF 100
task_urgent_font_color = #FFFFFF 100
task_iconified_font_color = #7B44CF 100
font_shadow = 0

# System Tray
systray = 1
systray_padding = 2 2 6
systray_sort = left2right
systray_background_id = 0
systray_icon_size = 0
systray_icon_asb = 100 -20 -22

# Clock
time1_format = %A   %Y-%m-%d   %H:%M
time1_font = Consolas 14
clock_font_color = #ADA59D 100
clock_padding = 0 0
clock_background_id = 0

# Tooltips
tooltip = 1
tooltip_padding = 5 5
tooltip_show_timeout = 0
tooltip_hide_timeout = 0
tooltip_background_id = 3
tooltip_font = Consolas 15
tooltip_font_color = #ADA59D 100

# End of config

</pre>

**Comment by jmc-88** [comment]
You have used this `panel_position` config:

```
panel_position = bottom left horizontal
```

I think you should use this instead:

```
panel_position = top left horizontal
```

It seems to work as intended in that case.  I'll close this bug for now, please reopen if there's something obvious I'm failing to see. :)

**Comment by jmc-88** [comment]
Actually, having `panel_position = bottom [...]` and the panel showing at the top is a problem per se.  I'll reopen this issue to track fixing that.

**Comment by Vakhrushev** [comment]
Ouu. I am apologize. 
i use 

<pre>
panel_dock = 1
</pre>

in openbox  panel_dock set at the top. 

in titn2 it work fine %)
