### ISSUE TITLE
X11 check fails on Arch

### ISSUE THREAD

**Issue by Lartza** [jmc-88/tint3#41]
Possibly due to cmake 3.14, although I don't see a breaking change at a glance. Build on Debian sid seems to work on 3.13.

```
CMake Error at /usr/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find X11 (missing: X11 Xrandr>=1.3)
Call Stack (most recent call first):
  /usr/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.14/Modules/FindX11.cmake:366 (find_package_handle_standard_args)
  CMakeLists.txt:45 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/tint3-cpp-git/src/tint3/CMakeFiles/CMakeOutput.log".
```

Using `Xcomposite Xdamage Xfixes Xinerama Xrender Xrandr)` the build succeeds.

**Comment by jmc-88** [comment]
The error is coming from `FindPackageHandleStandardArgs.cmake`, and a `git bisect` points at https://github.com/Kitware/CMake/commit/a7d2ffb2325478e4d242e3b7338f8ca1c1898ff7 which added the `find_package_handle_standard_args()` call to `FindX11.cmake`.

This sounds like a silent behavioral change, which is annoying, but at least it's easy to fix.

**Comment by bundlepax** [comment]
jmc-88 
I was having same problems using Linux Mint 20.
 I then switched to the older version of cmake 3.13. and still same issue just like with cmake 3.14

$  sudo cmake ..
-- Checking for modules 'x11;xcomposite;xdamage;xinerama;xext;xrender;xrandr>=1.3'
--   No package 'xcomposite' found
--   No package 'xdamage' found
--   No package 'xinerama' found
--   No package 'xext' found
--   No package 'xrender' found
--   No package 'xrandr' found
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  CMakeLists.txt:28 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/tint2/build/CMakeFiles/CMakeOutput.log".
See also "/tint2/build/CMakeFiles/CMakeError.log".

**Comment by jmc-88** [comment]
@bundlepax I'm having trouble following:

- Your output there mentions ` See also "/tint2/build/CMakeFiles/CMakeOutput.log"` which suggests you may be commenting on the wrong project? Try https://gitlab.com/o9000/tint2
- The error message is different from that of the original report in this ticket
- It almost sounds like you simply don't have those packages installed (or the relevant `-dev` versions of them, if any; I'm not sure as I've never used Linux Mint myself).
