### ISSUE TITLE
Keep it alive

### ISSUE THREAD

**Issue by tobimensch** [jmc-88/tint3#42]
I think this project was a good idea,
hopefully it can reach feature parity with tint2.

Kind Regards

**Comment by jmc-88** [comment]
Well, maybe.

Truth is, I was originally going for an incremental rewrite (keep the project code as is, rewrite piece by piece into something that I was hoping was more maintainable) to avoid breaking functionality, but it deserves a much more radical approach really, which is very time consuming. And I've been doing this for fun in my spare time, which is not plenty to begin with, and it's never gotten much traction, which doesn't incentivize me to invest more of that time into it. Furthermore, some time ago I stopped using my custom Openbox-based setup where tint3 had its place, and with that I lost also my direct personal interest in the project.

I haven't archived it or marked it as abandoned as I may go back to it eventually, but I guess don't hold your breath. If anybody wants to become a new maintainer, let me know.

**Comment by tobimensch** [comment]
@jmc-88 
I see. Currently I'm working on a desktop environment based on openbox, because I got fed up with gnome/kde's random issues. Actually I had this in the works for years, but now revived it, when it's ready maybe you can take a look at it, and maybe you'll get interested in tint3 again.

What was missing from your openbox based desktop that made you switch?

**Comment by jmc-88** [comment]
Openbox is just a window manager, so the rest of the "desktop" has to be stitched together -- which is fine, and I did that for years. But lately I settled on using elementary OS where the defaults match my expectations, so there's very little in the way of configuration that I need to tweak, and that leaves me more time for other stuff. Their desktop environment already includes a task panel, which makes tint3 redundant.

**Comment by tobimensch** [comment]
@jmc-88 
Well, basically I want to create a openbox distribution (that can be installed on any linux distribution) that does this stitching together for you. And once I upload this to github, maybe we'll get a community that improves it further, because as you say a freshly installed openbox setup is a lot of work to make it useful, and through this distribution approach the amount of work could be lowered. I like what I learned about Elementary OS, and definitely understand your decision to turn your back on something that can be time consuming.

**Comment by jmc-88** [comment]
I'd be curious to see the plans for this distribution. A lightweight Openbox-based environment is always nice to see, I liked the efforts from CrunchBang and later BunsenLabs, I may consider it for my aging laptop if your project roadmap looks nice. :smile: 

At the moment though the state for this project is what I described above. Not exactly dead, but not very alive either. I'd welcome external interest in maintaining it if any concrete plans to do so exist.

For now, does that answer address your concerns? If so I think we can close the conversation.

**Comment by tobimensch** [comment]
Yeah, thanks for your thoughts!
