### ISSUE TITLE
Tint 3 crashes in Bspwm

### ISSUE THREAD

**Issue by dedguy21** [jmc-88/tint3#43]
OS: Arch
Kernel: 5.9.9-zen
Tint3: v0.3.0
Bspwm: v0.9.10

1) Copied tint3rc to $HOME/.config/tint3 
2) initiate tint3 while inside bspwm (after it didn't start from script)

Stopped at: WM doesn't respect NETWM specs, tint3 will default to 1 desktop. 

Restarted loaded for a while then crashes

Real transparency: on, depth: 32
WM doesn't respect NETWM specs. tint3 will default to 1 desktop.
Segmentation fault (core dumped):

**Comment by jmc-88** [comment]
It dumped the core, so maybe you can see if there's a suspicious-looking stack trace there?

I can try to reproduce but I'm using neither Arch Linux nor Bspwm...

**Comment by dedguy21** [comment]
Definitely will. But just double checking, that this is tint3 EWMH compliant? Maybe that is an issue ...

**Comment by jmc-88** [comment]
"Compliant" is a strong word... :laughing: 

I didn't do anything regarding EWMH compliance specifically, so it's in the same state as the original tint2 code base was when I forked it. There's probably much that's lacking in that area.

**Comment by dedguy21** [comment]
Gotcha 😁

**Comment by jmc-88** [comment]
Reopening as the issue is not fixed. I'd like to try at least confirming if I can get it to crash under Bspwm.

**Comment by jmc-88** [comment]
I launched it under Bspwm and it didn't crash, but I'm also literally just running Bspwm without any customization -- something else must be causing the segmentation fault, or some specific configuration setting.

I'm going to close the report since I can't reproduce, let me know if you have more data and I'll investigate further.

**Comment by dedguy21** [comment]
I have a dual monitor setup. Maybe that's the reason?

**Comment by jmc-88** [comment]
Still can't reproduce, I tried a simulated dual monitor via Xephyr like so (approximating):

```
$ Xephyr :1 -screen 640x480 -screen 640x480 -retro & disown
$ env DISPLAY=:1 bspwm & disown
$ build/tint3 -c sample/tint3rc
```

Perhaps it's something that has to do with the configuration you're using?
If your system uses systemd and has coredumps enabled, you can try something like this right after tint3 crashes:

```
$ coredumpctl dump -o tint3.core
```

That would also print out the termination data, including termination signal and stack trace. That may narrow the scope a little.
