### ISSUE TITLE
No tray in second open

### ISSUE THREAD

**Issue by ggg377** [jmc-88/tint3#6]
Steps to reproduce:
tint3 -c configfile
killall tint3
tint3 -c configfile

Doesn't occur when I autostart tint3 with openbox, kill the bugged bar (see issue below) and start a new one. Upon killing the new bar, this will occur.

**Comment by jmc-88** [comment]
I think I've fixed this issue in https://github.com/jmc-88/tint3/commit/cb59a927ae30c5d7acd22b68613cd63788af4617.

I'm closing this issue. Please try a build from HEAD and reopen the issue if it's still present.
