### ISSUE TITLE
Running Qpdfview immediately after logon causes icon duplication in system tray

### ISSUE THREAD

**Issue by mcfadzgit** [jmc-88/tint3#9]
When I run Qpdfview (0.4.14) immediately after logon, an icon in the system tray - usually that of the NetworkManager applet or Pasystray - gets duplicated and sometimes some graphical junk also appears in the system tray. When I reload Tint3's configuration (killall -SIGUSR1 tint3), or load Qpdfview later in the logon session, everything seems okay. (I also tried with sqlitebrowser - another Qt5 program - and it didn't seem to cause a problem.)
Qpdfview definitely seems the worst culprit, for some reason.

Note: I had occasional problems with Tint2 duplicating icons too, but can't recall any special circumstances or programs involved. Again, reloading Tint2's configuration cleared the problem.

**Comment by jmc-88** [comment]
Thanks for the report. I'll try reproducing this on my machine later today and see what I can do.

**Comment by jmc-88** [comment]
I seem unable to reproduce this problem with a build at master HEAD of tint3. I've used the tint3rc you attached in https://github.com/jmc-88/tint3/issues/7, and I have both nm-applet an pasystray running: opening Qpdfview (0.4.15, but I guess it doesn't explain the difference) and any PDF file seems to work just fine.

Are you running the latest Git build? What is the output of `tint3 --version`?

**Comment by mcfadzgit** [comment]
Hi - Have upgraded to qpdfview 0.4.15 and latest tint3-cpp-git-r749.8a28eb9 (was running at previous commit level). `tint3 --version` returns: tint3 (v0.01)
Unfortunately, I am still getting a duplicated icon (pasystray on the last occasion) as before, but **only when I run qpdfview for the first time immediately after logging on** (the file loaded seems immaterial). After reloading the tint3 configuration I never get the problem again later in the login session.
Very strange ...
PS: I should have mentioned that I am using PCManFM for managing the desktop.

**Comment by jmc-88** [comment]
Tried launching `pcmanfm --desktop` too at the start of the session, no luck reproducing the issue. :(

**Comment by mcfadzgit** [comment]
Not a show-stopper, so for now will clear occasional duplicated icon with `killall -SIGUSR1 tint3` and close issue.
